base/urls.py
from django.conf.urls import url
from base import views

__author__ = 'ahmetdal'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^results/(?P<pk>\d+)/$', views.ResultsView.as_view(), name='results'),
    url(r'^vote/(?P<question_id>\d+)/$', views.VoteView.as_view(), name='vote'),
    url(r'^question/$', views.QuestionView.as_view(), name='question'),
    url(r'^choice/(?P<question_id>\d+)/$', views.ChoiceView.as_view(), name='choice'),

]

survey/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('base.urls', namespace='base')),
]

base/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(verbose_name="Question", max_length=500)
    pub_date = models.DateTimeField("Publish Date", auto_now_add=True)

    def __str__(self):
        return self.question_text

    @property
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text


Question.objects.filter()

base/forms.py
from base.models import Question, Choice

__author__ = 'ahmetdal'
from django import forms


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['question', 'choice_text']

base/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import View
from base.forms import QuestionForm, ChoiceForm
from base.models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'results.html'


class QuestionView(View):
    def get(self, request):
        question_form = QuestionForm()
        return render(request, 'add_question.html', {
            'question_form': question_form,
        })

    def post(self, request):
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question_form.save()
            return HttpResponseRedirect(reverse('base:index'))
        else:
            return render(request, 'add_question.html', {
                'question_form': question_form,
                'errors': question_form.errors
            })


class ChoiceView(View):
    def dispatch(self, request, question_id, *args, **kwargs):
        self.question = Question.objects.get(pk=question_id)
        return super(ChoiceView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        choice_form = ChoiceForm(initial={'question': self.question})
        return render(request, 'add_choice.html', {
            'question': self.question,
            'choice_form': choice_form,
        })

    def post(self, request, *args, **kwargs):
        choice_form = ChoiceForm(request.POST, initial={'question': self.question})
        if choice_form.is_valid():
            choice_form.save()
            return HttpResponseRedirect(reverse('base:detail', args=(choice_form.cleaned_data.get('question').pk,)))
        else:
            return render(request, 'add_choice.html', {
                'question': self.question,
                'choice_form': choice_form,
                'errors': choice_form.errors
            })


class VoteView(View):
    def __init__(self):
        self.output = ''

    def dispatch(self, request, *args, **kwargs):
        return super(VoteView, self).dispatch(request, *args, **kwargs)

    def get(self, request, question_id):
        raise Http404("Not Found")

    def post(self, request, question_id, *args, **kwargs):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'detail.html', {
                'question': question,
                'error_message': "You didn't select a choice."
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('base:results', args=(question.id,)))

base/templates/add_choice.html
{% extends 'master.html' %}

{% block content %}
  <h1>Add Choice Page</h1>

  {% if errors %}
    {% for key,error in errors.iteritems %}
      {{ key }}: {{ error }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}

    <div>
      <label for="question_text">Question</label>
      {{ choice_form.question }}
    </div>
    <div>
      <label for="question_text">Choice</label>
      {{ choice_form.choice_text }}
    </div>
    <div>
      <input type="submit" value="Save"/>
    </div>

  </form>
{% endblock %}

base/templates/add_question.html
{% extends 'master.html' %}
{% block content %}
  <h1>Add Question Page</h1>

  {% if errors %}
    {% for key,error in errors.iteritems %}
      {{ key }}: {{ error }}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="question_text">Question</label>
    {{ question_form.question_text }}
    <input type="submit" value="Save"/>
  </form>
{% endblock %}

base/templates/detail.html
{% extends 'master.html' %}
{% block content %}
  <h1>{{ question.question_text }}</h1>

  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <form action="{% url 'base:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>

    <br/>
    <br/>

    <a href="{% url 'base:choice' question.pk %}">Create Choice</a>
  </form>

{% endblock %}

base/templates/index.html
{% if latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
      {#      <li><a href="/base/detail/{{ question.id }}/">{{ question.question_text }}</a></li>#}
      <li><a href="{% url 'base:detail' question.pk %}">{{ question.question_text }}</a></li>
    {% endfor %}
  </ul>
  <br/>
  <br/>
  <a href="{% url 'base:question' %}">Create Question</a>
{% else %}
  <p>No base are available.</p>
{% endif %}

base/templates/master.html
<a href="{% url 'base:index' %}">Home Page</a>
<br/>

{% block content %}

{% endblock %}

base/templates/results.html
{% extends 'master.html' %}

{% block content %}

  <h1>{{ question.question_text }}</h1>

  <ul>
    {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
  </ul>

  <a href="{% url 'base:detail' question.id %}">Vote again?</a>

{% endblock %}